# Generated by Django 6.1 on 2026-09-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
