# Generated by Django 6.1 on 2026-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_whatsapp_phone_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
