# Generated by Django 6.1 on 2026-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number_id', models.CharField(help_text='The WhatsApp Phone Number ID assigned to this specific campaign tenant.', max_length=100, unique=True)),
                ('waba_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
