# Generated by Django 6.1 on 2026-09-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaignstaff'),
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='political_allegiance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supporter',
            name='registration_step',
            field=models.CharField(default='START', max_length=50),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
